spring:
  datasource:
    # url: jdbc:mysql:///maricota-doces-database?cloudSqlInstance=maricota-doces-305313:us-central1:maricota-doces-database&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=root&password=5611d2906.
    password: 5611d2906.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    gcp:
      sql:
        database-name: maricota-doces-database
        instance-connection-name: maricota-doces-305313:us-central1:maricota-doces-database
