# spring:
#   profiles:
#     active: "development"

# ---

# ## PROD
# spring:
#   profiles: production
#   datasource:
#     url: jdbc:mysql://35.188.45.216:3306/maricota_doces
#     username: root
#     password: 5611d2906.
#     hikari:
#       maximum-pool-size: 10
#     driverClassName: com.mysql.jdbc.Driver
#   jpa:
#     hibernate:
#       ddl-auto: none
#     show-sql: true

# ---

# ## DEV
spring:
  # profiles: development
  datasource:
    url: jdbc:mysql:///maricota_doces?cloudSqlInstance=maricota-doces-81756:us-central1:maricota-doces-instance&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=root&password=3759112Dd.
    username: root
    password: 3759112Dd.
    drive-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true