
spring:
  datasource:
    url: jdbc:h2:~/maricota-doces;DB_CLOSE_ON_EXIT=FALSE
    username: maricota
    password: doces
    drive-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true